// Typed contract for an evaluation. Originally mirrored promptforge/schema.py (Python CLI)
// with a fixed four-dimension scorecard; the web app now supports multiple prompt frameworks
// (see lib/frameworks.ts), so the scorecard is a dynamic, ordered list of dimensions whose
// keys/names come from the selected framework. `overall_score` is computed server-side
// (scoring.ts), never from the model.
import * as z from "zod/v4";

export const SCORES = ["Poor", "Needs Work", "Good", "Excellent"] as const;
export const ScoreSchema = z.enum(SCORES);
export type Score = (typeof SCORES)[number];

// What the model returns for a single dimension. The dimension's identity (key + display
// name) is supplied by the framework definition, not the model, so it lives outside this
// schema — the model only judges the prompt.
export const DimensionResultSchema = z.object({
  score: ScoreSchema.describe("Poor / Needs Work / Good / Excellent"),
  assessment: z.string().describe("1-2 sentences explaining the score"),
  advice: z.string().describe("one specific, actionable improvement"),
});
export type DimensionResult = z.infer<typeof DimensionResultSchema>;

// A scored dimension as the rest of the app consumes it: the model's judgement plus the
// framework-supplied key (stable id) and name (display label).
export type Dimension = DimensionResult & { key: string; name: string };
export type Scorecard = Dimension[];

// Scalar fields shared by every framework's evaluation schema. The `scorecard` field is
// built per-framework (buildEvaluationSchema in lib/frameworks.ts) and merged with these.
//
// `prompt_evaluated` is deliberately NOT here: the model used to be asked to repeat the
// user's draft verbatim, which billed the whole input again as output tokens and — since
// latency here is almost entirely output generation — delayed every other field behind it.
// The route fills it from the request instead, for free.
export const EVALUATION_SCALAR_FIELDS = {
  priority_fix: z.string().describe("the single most impactful change to make first"),
  revised_prompt: z.string().describe("the full rewritten prompt, ready to use"),
  suggested_title: z
    .string()
    .describe("a short 3-6 word descriptive title naming what the prompt does"),
  suggested_category: z.string().describe("a single short category for filing"),
  suggested_tags: z.array(z.string()).describe("2-5 short lowercase tags for search"),
} as const;

// The full evaluation as consumed by the app. The model produces the scalar fields plus a
// scorecard keyed by the framework's dimension keys; the engine reshapes that into the
// ordered `Scorecard` array and attaches which framework produced it.
export type Evaluation = {
  /** The draft that was evaluated. Echoed back by the route, not generated by the model. */
  prompt_evaluated: string;
  scorecard: Scorecard;
  priority_fix: string;
  revised_prompt: string;
  suggested_title: string;
  suggested_category: string;
  suggested_tags: string[];
  framework: { id: string; name: string };
};

export type EvaluationResult = {
  evaluation: Evaluation;
  overall_score: Score;
};
